# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    all-github-actions:
      patterns: [ "*" ]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

# Go modules
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  # group all dependencies with a k8s.io prefix into a single PR.
  groups:
    all-go-mod-patch-and-minor:
      patterns: [ "*" ]
      update-types: [ "patch", "minor" ]
  ignore:
  # Ignore k8s and its transitives modules as they are upgraded manually.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  commit-message:
    prefix: ":seedling:"
  labels:
    - "ok-to-test"
